global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.5.100:9090']
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.5.100
    metrics_path: /snmp
    params:
      module: [if_mib]
      #module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '192.168.5.100:9116'  # SNMP exporter.
